#!/usr/bin/env python3
"""Create music.fdb Firebird database from Thai catalog seed data."""

import subprocess
import os

ISQL = "/Library/Frameworks/Firebird.framework/Versions/A/Resources/bin/isql"
DB_PATH = "/Users/worajedt/Xojo Projects/FirebirdPlugin/music.fdb"

# Remove existing database if present
if os.path.exists(DB_PATH):
    os.remove(DB_PATH)
    print(f"Removed existing {DB_PATH}")

# ── Step 1: Create database ──────────────────────────────────────────────
create_sql = f"""
CREATE DATABASE 'localhost:{DB_PATH}'
  USER 'SYSDBA' PASSWORD 'masterkey'
  DEFAULT CHARACTER SET UTF8;
"""
proc = subprocess.run([ISQL, "-q", "-user", "SYSDBA", "-password", "masterkey"],
                      input=create_sql, capture_output=True, text=True)
if proc.returncode != 0:
    print("CREATE DATABASE failed:", proc.stderr)
    exit(1)
print("Database created.")

# ── Step 2: Schema + Data ────────────────────────────────────────────────
schema_and_data = r"""
/* ── Schema ─────────────────────────────────────────────────────── */

CREATE TABLE genres (
    GenreId INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(200) NOT NULL
);

CREATE TABLE media_types (
    MediaTypeId INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(200) NOT NULL
);

CREATE TABLE artists (
    ArtistId INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(200) NOT NULL
);

CREATE TABLE albums (
    AlbumId INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Title VARCHAR(400) NOT NULL,
    ArtistId INTEGER NOT NULL REFERENCES artists(ArtistId)
);

CREATE TABLE tracks (
    TrackId INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(400) NOT NULL,
    AlbumId INTEGER REFERENCES albums(AlbumId),
    MediaTypeId INTEGER NOT NULL REFERENCES media_types(MediaTypeId),
    GenreId INTEGER REFERENCES genres(GenreId),
    Composer VARCHAR(400),
    Milliseconds INTEGER NOT NULL,
    Bytes INTEGER,
    UnitPrice DECIMAL(10,2) NOT NULL
);

CREATE TABLE playlists (
    PlaylistId INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(200) NOT NULL
);

CREATE TABLE playlist_track (
    PlaylistId INTEGER NOT NULL REFERENCES playlists(PlaylistId),
    TrackId INTEGER NOT NULL REFERENCES tracks(TrackId),
    PRIMARY KEY (PlaylistId, TrackId)
);

COMMIT;

/* ── Seed: genres & media types ─────────────────────────────────── */

INSERT INTO genres (GenreId, Name) VALUES (1, 'Rock');
INSERT INTO genres (GenreId, Name) VALUES (2, 'Pop');
INSERT INTO genres (GenreId, Name) VALUES (3, 'Country');

INSERT INTO media_types (MediaTypeId, Name) VALUES (1, 'MPEG audio file');

COMMIT;

/* ── Seed: artists ──────────────────────────────────────────────── */
/* Batch 1 (seed_thai_catalog) */
INSERT INTO artists (ArtistId, Name) VALUES (1, 'Bodyslam');
INSERT INTO artists (ArtistId, Name) VALUES (2, 'Bird Thongchai');
INSERT INTO artists (ArtistId, Name) VALUES (3, 'Carabao');
/* Batch 2 (seed_thai_catalog_thai_script) */
INSERT INTO artists (ArtistId, Name) VALUES (4, 'ไมโคร');
INSERT INTO artists (ArtistId, Name) VALUES (5, 'อำพล ลำพูน');
INSERT INTO artists (ArtistId, Name) VALUES (6, 'ป้าง นครินทร์ กิ่งศักดิ์');
INSERT INTO artists (ArtistId, Name) VALUES (7, 'กบ ทรงสิทธิ์');
INSERT INTO artists (ArtistId, Name) VALUES (8, 'ฝน ธนสุนทร');
INSERT INTO artists (ArtistId, Name) VALUES (9, 'ต่าย อรทัย');
INSERT INTO artists (ArtistId, Name) VALUES (10, 'ไผ่ พงศธร');
INSERT INTO artists (ArtistId, Name) VALUES (11, 'เสถียร ทำมือ');
INSERT INTO artists (ArtistId, Name) VALUES (12, 'หญิง ธิติกานต์');
INSERT INTO artists (ArtistId, Name) VALUES (13, 'สุนารี ราชสีมา');

COMMIT;

/* ── Seed: albums ───────────────────────────────────────────────── */
INSERT INTO albums (AlbumId, Title, ArtistId) VALUES (1, 'believe', 1);
INSERT INTO albums (AlbumId, Title, ArtistId) VALUES (2, 'บูมเมอแรง', 2);
INSERT INTO albums (AlbumId, Title, ArtistId) VALUES (3, 'เมด อิน ไทยแลนด์', 3);
INSERT INTO albums (AlbumId, Title, ArtistId) VALUES (4, 'ร็อค เล็ก เล็ก', 4);
INSERT INTO albums (AlbumId, Title, ArtistId) VALUES (5, 'ม้าเหล็ก', 5);
INSERT INTO albums (AlbumId, Title, ArtistId) VALUES (6, 'ไข้ป้าง', 6);
INSERT INTO albums (AlbumId, Title, ArtistId) VALUES (7, 'กบใส ๆ', 7);
INSERT INTO albums (AlbumId, Title, ArtistId) VALUES (8, 'รักหมดใจ', 8);
INSERT INTO albums (AlbumId, Title, ArtistId) VALUES (9, 'ต่าย อรทัย ลำนำดอกหญ้า', 9);
INSERT INTO albums (AlbumId, Title, ArtistId) VALUES (10, 'ชุดที่ 3 อยากบอกว่าอ้ายเหงา', 10);
INSERT INTO albums (AlbumId, Title, ArtistId) VALUES (11, 'ชุดที่ 4 โดยสารมากับกำลังใจ', 11);
INSERT INTO albums (AlbumId, Title, ArtistId) VALUES (12, 'มายาแห่งความรัก', 12);
INSERT INTO albums (AlbumId, Title, ArtistId) VALUES (13, 'สุนารี ซูเปอร์ฮิต', 13);

COMMIT;

/* ── Seed: tracks ───────────────────────────────────────────────── */
/* Album 1: Bodyslam – believe (Rock) */
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ชีวิตเป็นของเรา', 1, 1, 1, 230053, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ขอบฟ้า', 1, 1, 1, 256253, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('คนที่ถูกรัก', 1, 1, 1, 282827, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ความรักทำให้คนตาบอด', 1, 1, 1, 222267, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ความเชื่อ (feat. แอ๊ด คาราบาว)', 1, 1, 1, 297093, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('พูดในใจ', 1, 1, 1, 226893, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('รักก็เป็นอย่างนี้', 1, 1, 1, 208213, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ห้ามใจ', 1, 1, 1, 267627, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ไม่รู้เมื่อไหร่', 1, 1, 1, 248653, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เจ็บจนวันนี้', 1, 1, 1, 202360, 0.99);

/* Album 2: Bird Thongchai – บูมเมอแรง (Pop) */
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('บูมเมอแรง', 2, 1, 2, 209613, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('คู่กัด', 2, 1, 2, 180813, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เงียบๆ คนเดียว', 2, 1, 2, 244520, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('คืนนี้ไม่เหมือนคืนนั้น', 2, 1, 2, 226133, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เงาที่หายไป', 2, 1, 2, 204227, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('บ้านของเรา', 2, 1, 2, 73627, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('พักตรงนี้', 2, 1, 2, 201133, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('หมอกหรือควัน', 2, 1, 2, 187907, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('อย่าหลบตากัน', 2, 1, 2, 284867, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ภารตี', 2, 1, 2, 214533, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ต่อเวลา', 2, 1, 2, 205053, 0.99);

/* Album 3: Carabao – เมด อิน ไทยแลนด์ (Country) */
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เมด อิน ไทยแลนด์', 3, 1, 3, 251693, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('มหาลัย', 3, 1, 3, 243747, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ลูกหิน', 3, 1, 3, 245573, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ลูกแก้ว', 3, 1, 3, 206040, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('หำเทียม', 3, 1, 3, 243107, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('สองเฒ่าผู้ยิ่งใหญ่', 3, 1, 3, 238213, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ราชาเงินผ่อน', 3, 1, 3, 207280, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('นางงามตู้กระจก', 3, 1, 3, 275107, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เรฟูจี', 3, 1, 3, 277920, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('บัวลอย (ถึกควายทุย ภาค 5)', 3, 1, 3, 275493, 0.99);

/* Album 4: ไมโคร – ร็อค เล็ก เล็ก (Rock) */
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('อย่าดีกว่า', 4, 1, 1, 204813, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('อู๊ดกับแอ๊ด', 4, 1, 1, 218200, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('รักปอนปอน', 4, 1, 1, 240907, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('อยากจะบอกใครซักคน', 4, 1, 1, 244720, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เรามันก็เป็นอย่างนี้', 4, 1, 1, 255027, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('สมน้ำหน้า..ซ่าส์..นัก', 4, 1, 1, 229267, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ฝันที่อยู่ไกล', 4, 1, 1, 259267, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('อยากได้ดี', 4, 1, 1, 219307, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('จำฝังใจ', 4, 1, 1, 274067, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ลุง', 4, 1, 1, 200147, 0.99);

/* Album 5: อำพล ลำพูน – ม้าเหล็ก (Rock) */
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ม้าเหล็ก', 5, 1, 1, 305333, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เอากะเขาหน่อย', 5, 1, 1, 283000, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ลองเชิงลองใจ', 5, 1, 1, 281000, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ไม่อยากทำใคร', 5, 1, 1, 292333, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('จะไปเหลืออะไรล่ะ', 5, 1, 1, 264333, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ขอเวลาหายใจ', 5, 1, 1, 295667, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('รู้ได้ยังไง', 5, 1, 1, 288493, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ไว้ใจ', 5, 1, 1, 276373, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ไม่ต้องเกรงใจกันบ้าง', 5, 1, 1, 244173, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เครื่องจักรน้อยๆ', 5, 1, 1, 241000, 0.99);

/* Album 6: ป้าง นครินทร์ กิ่งศักดิ์ – ไข้ป้าง (Rock) */
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('สบายดี', 6, 1, 1, 247333, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ปีหน้า', 6, 1, 1, 223000, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เอื้อมไม่ถึง', 6, 1, 1, 230733, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('คุยกับตัวเอง', 6, 1, 1, 210933, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ประตู', 6, 1, 1, 200960, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ที่ว่าการอำเภอ', 6, 1, 1, 260467, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('คำตอบ', 6, 1, 1, 218040, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('นานๆ ที', 6, 1, 1, 202427, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('วันที่เลวร้าย', 6, 1, 1, 250000, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เลิกคอย', 6, 1, 1, 114040, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('อยากเด็ก', 6, 1, 1, 174320, 0.99);

/* Album 7: กบ ทรงสิทธิ์ – กบใส ๆ (Pop) */
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('วันใส ๆ', 7, 1, 2, 219693, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('รักกันหน่อย', 7, 1, 2, 239707, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ปาฏิหาริย์', 7, 1, 2, 247573, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ต่างคนต่างใจ', 7, 1, 2, 212840, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เกิดมาพร้อมกับคำว่าผู้ชาย', 7, 1, 2, 221627, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เติมไม่เต็ม', 7, 1, 2, 217733, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ช่างเถอะ', 7, 1, 2, 245200, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ทะลุกลางใจ', 7, 1, 2, 240227, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('รักหรือไม่รัก', 7, 1, 2, 232867, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('สวยเกรดซี', 7, 1, 2, 229293, 0.99);

/* Album 8: ฝน ธนสุนทร – รักหมดใจ (Country) */
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('รักต้องห้าม', 8, 1, 3, 216653, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ว้าเหว่', 8, 1, 3, 193653, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ใจคนคอย', 8, 1, 3, 174440, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('รักหมดใจ', 8, 1, 3, 184440, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ระฆังใจ', 8, 1, 3, 204547, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ดั่งนกเจ็บ', 8, 1, 3, 221427, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ไฟเสน่หา', 8, 1, 3, 196373, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('คอย', 8, 1, 3, 206440, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('สายัณห์รัญจวน', 8, 1, 3, 223387, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('แหวนแลกใจ', 8, 1, 3, 234493, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('สายเกินไป', 8, 1, 3, 179427, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ฝันฝัน', 8, 1, 3, 191427, 0.99);

/* Album 9: ต่าย อรทัย – ต่าย อรทัย ลำนำดอกหญ้า (Country) */
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ดอกหญ้าในป่าปูน', 9, 1, 3, 229027, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('จากบ้านนาด้วยรัก', 9, 1, 3, 231000, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ดาวเต้น ม. ต้น', 9, 1, 3, 248240, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('คนไกลเบอร์เก่า', 9, 1, 3, 260227, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ขอสิทธิ์แค่ร้องไห้', 9, 1, 3, 284467, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('บอกใจยังไงดี', 9, 1, 3, 273173, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('วันที่บ่มีอ้าย', 9, 1, 3, 253720, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ให้ตายไปกับใจ', 9, 1, 3, 240333, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ทรายกับทะเล', 9, 1, 3, 270373, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('แอบรักแอบคิดถึง', 9, 1, 3, 261147, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('หน้าจอรอสาย', 9, 1, 3, 256053, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('คูนดอกสุดท้าย', 9, 1, 3, 249253, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('อยากลืมแฟนเขา', 9, 1, 3, 232840, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เอิ้นสั่งหลังสงกรานต์', 9, 1, 3, 239667, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('กินข้าวหรือยัง', 9, 1, 3, 245600, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('นอนฟังเสียงฝน', 9, 1, 3, 263920, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('โทรหาแหน่เด๊อ', 9, 1, 3, 234573, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('สาวนาพเนจร', 9, 1, 3, 239493, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('กรรมกรแก้มแดง', 9, 1, 3, 236773, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('กำแพงปริญญา', 9, 1, 3, 235200, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ตั๋วให้คึดฮอด', 9, 1, 3, 250427, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ขอใจกันหนาว', 9, 1, 3, 266493, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('คนใกล้เมื่อไกลบ้าน', 9, 1, 3, 237093, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('คือฮักหรือบ่', 9, 1, 3, 255653, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ขอแค่รู้ข่าว', 9, 1, 3, 251267, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เพื่อนกันโรงงานเก่า', 9, 1, 3, 248773, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ฝากเพลงถึงยาย', 9, 1, 3, 242507, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('อยู่ในใจเสมอ', 9, 1, 3, 255627, 0.99);

COMMIT;

/* Album 10: ไผ่ พงศธร – ชุดที่ 3 อยากบอกว่าอ้ายเหงา (Country) */
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('กลับมาถามหากำลังใจ', 10, 1, 3, 268987, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('คนบ้านเดียวกัน', 10, 1, 3, 263987, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('บังเอิญมีหัวใจ', 10, 1, 3, 261987, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ซ้อนมอเตอร์ไซค์ไปก่อน', 10, 1, 3, 251293, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('อยากบอกว่าอ้ายเหงา', 10, 1, 3, 274987, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ฝากดาวดวงนั้น', 10, 1, 3, 265987, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('กลัวว่าจะลืม', 10, 1, 3, 258613, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ภาวนา', 10, 1, 3, 253653, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ขี้เหงาเมืองกรุง', 10, 1, 3, 270333, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ยังจำได้ไหม', 10, 1, 3, 248987, 0.99);

/* Album 11: เสถียร ทำมือ – ชุดที่ 4 โดยสารมากับกำลังใจ (Country) */
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('โดยสารมากับกำลังใจ', 11, 1, 3, 270333, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ขอจองนะ', 11, 1, 3, 251293, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เกินจะทน', 11, 1, 3, 248987, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ฝากรัก', 11, 1, 3, 261987, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('กลัวเสียเธอ', 11, 1, 3, 253653, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('คนเจ้าน้ำตา', 11, 1, 3, 265987, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ความลับในใจ', 11, 1, 3, 258613, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('บอกตัวเองว่าไม่เป็นไร', 11, 1, 3, 268987, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('จดหมายจากบ้าน', 11, 1, 3, 263987, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ฝันดีนะ', 11, 1, 3, 274987, 0.99);

/* Album 12: หญิง ธิติกานต์ – มายาแห่งความรัก (Country) */
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('มายาแห่งความรัก', 12, 1, 3, 258613, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ยิ่งรักยิ่งเจ็บ', 12, 1, 3, 248987, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ปล่อยมือฉันได้แล้ว', 12, 1, 3, 261987, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ดอกไม้ริมทาง', 12, 1, 3, 253653, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('อยู่ตรงนี้นานกว่านี้', 12, 1, 3, 270333, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ลืมฉันแล้วเหรอ', 12, 1, 3, 265987, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('น้ำตาหล่นบนที่นอน', 12, 1, 3, 251293, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('รักคนไม่จริง', 12, 1, 3, 274987, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ขอโทษที่เป็นแบบนี้', 12, 1, 3, 268987, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('สุดท้ายก็คนเดียว', 12, 1, 3, 263987, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เหงาจนเคยชิน', 12, 1, 3, 258613, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ทำไมต้องเธอ', 12, 1, 3, 248987, 0.99);

/* Album 13: สุนารี ราชสีมา – สุนารี ซูเปอร์ฮิต (Country) */
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ผู้สาวขาเลาะ', 13, 1, 3, 229027, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('สาวนาสั่งแฟน', 13, 1, 3, 231000, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ตั๊กแตนผูกโบว์', 13, 1, 3, 248240, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('หัวใจมีตีน', 13, 1, 3, 260227, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('สุดเขตเสน่หา', 13, 1, 3, 284467, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ลูกสาวผู้ใหญ่บ้าน', 13, 1, 3, 273173, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('คนมีเสน่ห์', 13, 1, 3, 253720, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('อย่าเห็นกงจักรเป็นดอกบัว', 13, 1, 3, 240333, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ดาวเรืองดาวโรย', 13, 1, 3, 270373, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('แรงอธิษฐาน', 13, 1, 3, 261147, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ทองไม่รู้ร้อน', 13, 1, 3, 256053, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('หม้อแกงถังข้าว', 13, 1, 3, 249253, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ของปลอมไม่ได้ใส', 13, 1, 3, 232840, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('น้ำตาลาไทร', 13, 1, 3, 239667, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ช่างชุ่ย', 13, 1, 3, 245600, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('คนใจบาป', 13, 1, 3, 263920, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('สาวชาวไร่', 13, 1, 3, 234573, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('หนุ่มมหาลัย', 13, 1, 3, 239493, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ปลาทูนึ่งส้มตำ', 13, 1, 3, 236773, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('อยากจะร้องดัง ๆ', 13, 1, 3, 235200, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ผ่านมาผ่านไป', 13, 1, 3, 250427, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('จันทร์เอ๋ย', 13, 1, 3, 266493, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('หนีห่าง', 13, 1, 3, 237093, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('กลัวฉันหรือเปล่า', 13, 1, 3, 255653, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ภาพลวงตา', 13, 1, 3, 251267, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เกลียดคนข้างกาย', 13, 1, 3, 248773, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('คนเลี้ยงช้าง', 13, 1, 3, 242507, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('รักสามเส้า', 13, 1, 3, 255627, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('ก้นครัว', 13, 1, 3, 229027, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('เงาฝัน', 13, 1, 3, 231000, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('อดีตเกินลืม', 13, 1, 3, 248240, 0.99);
INSERT INTO tracks (Name, AlbumId, MediaTypeId, GenreId, Milliseconds, UnitPrice) VALUES ('สาวสวนแตง', 13, 1, 3, 260227, 0.99);

COMMIT;

/* ── Seed: playlists ────────────────────────────────────────────── */
INSERT INTO playlists (PlaylistId, Name) VALUES (1, 'Thai Essentials');
INSERT INTO playlists (PlaylistId, Name) VALUES (2, 'เพลงไทยล้วน');

/* Add all tracks from albums 1-3 to Thai Essentials (playlist 1) */
INSERT INTO playlist_track (PlaylistId, TrackId)
  SELECT 1, t.TrackId FROM tracks t
  JOIN albums a ON a.AlbumId = t.AlbumId
  WHERE a.AlbumId IN (1, 2, 3);

/* Add all tracks from albums 4-13 to เพลงไทยล้วน (playlist 2) */
INSERT INTO playlist_track (PlaylistId, TrackId)
  SELECT 2, t.TrackId FROM tracks t
  JOIN albums a ON a.AlbumId = t.AlbumId
  WHERE a.AlbumId BETWEEN 4 AND 13;

COMMIT;

/* ── Restart IDENTITY generators so next auto-ID doesn't collide ── */
ALTER TABLE genres ALTER COLUMN GenreId RESTART WITH 4;
ALTER TABLE media_types ALTER COLUMN MediaTypeId RESTART WITH 3;
ALTER TABLE artists ALTER COLUMN ArtistId RESTART WITH 14;
ALTER TABLE albums ALTER COLUMN AlbumId RESTART WITH 14;
ALTER TABLE tracks ALTER COLUMN TrackId RESTART WITH 177;
ALTER TABLE playlists ALTER COLUMN PlaylistId RESTART WITH 3;
COMMIT;
"""

proc = subprocess.run(
    [ISQL, "-q", "-ch", "UTF8", "-user", "SYSDBA", "-password", "masterkey", f"localhost:{DB_PATH}"],
    input=schema_and_data,
    capture_output=True,
    text=True,
)
if proc.returncode != 0:
    print("Schema/data failed:")
    print(proc.stderr)
    print(proc.stdout)
    exit(1)

print("Schema created and data seeded.")

# ── Step 3: Verify ───────────────────────────────────────────────────────
verify_sql = """
SELECT 'artists' AS tbl, COUNT(*) AS cnt FROM artists
UNION ALL SELECT 'albums', COUNT(*) FROM albums
UNION ALL SELECT 'tracks', COUNT(*) FROM tracks
UNION ALL SELECT 'genres', COUNT(*) FROM genres
UNION ALL SELECT 'playlists', COUNT(*) FROM playlists
UNION ALL SELECT 'playlist_track', COUNT(*) FROM playlist_track;
"""
proc = subprocess.run(
    [ISQL, "-q", "-ch", "UTF8", "-user", "SYSDBA", "-password", "masterkey", f"localhost:{DB_PATH}"],
    input=verify_sql,
    capture_output=True,
    text=True,
)
print("\nRow counts:")
print(proc.stdout)

# Quick Thai text test
thai_sql = "SELECT FIRST 3 a.Name, al.Title FROM artists a JOIN albums al ON al.ArtistId = a.ArtistId WHERE a.ArtistId > 3;\n"
proc = subprocess.run(
    [ISQL, "-q", "-ch", "UTF8", "-user", "SYSDBA", "-password", "masterkey", f"localhost:{DB_PATH}"],
    input=thai_sql,
    capture_output=True,
    text=True,
)
print("Thai text sample:")
print(proc.stdout)

print(f"\nDone! Database: {DB_PATH}")
